[package]
name = "ray"
version = "0.1.0"
edition = "2021"
authors = ["Jarmo Riikonen <amatrelan@gmail.com>"]
homepage = "https://github.com/Amatrelan/ray"

[dependencies]
better-panic = "0.3.0"
clap = { version = "4.4.6", features = ["derive"] }
color-eyre = "0.6.2"
human-panic = "1.2.1"
strip-ansi-escapes = "0.2.0"
tracing = "0.1.39"
tracing-subscriber = "0.3.17"
