edition = "2021"

group_imports = "StdExternalCrate"
imports_granularity = "Crate"

condense_wildcard_suffixes = true

enum_discrim_align_threshold = 10
struct_field_align_threshold = 10

format_code_in_doc_comments = true
